name: Build Release

on: 
  workflow_dispatch:

jobs:

  # リポジトリ設定の検証
  config:
    runs-on: ubuntu-latest
    outputs:
      config_package: ${{ steps.config_package.outputs.configPackage }}
    steps:

    # パッケージのために必要なリポジトリ変数が作成されていることを確認
    - name: パッケージ設定の検証
      id: config_package
      run: |
        if [ "${{ vars.PACKAGE_NAME }}" != "" ]; then
          echo "configPackage=true" >> $GITHUB_OUTPUT;
        else
          echo "configPackage=false" >> $GITHUB_OUTPUT;
        fi

  # パッケージのビルドとリリース
  # リポジトリが正しく設定されていない場合、このジョブはスキップされます
  build:
    needs: config
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      packagePath: Packages/${{ vars.PACKAGE_NAME }}
    if: needs.config.outputs.config_package == 'true'
    steps:

      # ローカルリポジトリのチェックアウト
      - name: チェックアウト
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac

      # package.jsonファイルに基づいてパッケージのバージョンを取得
      - name: バージョンの取得
        id: version
        uses: zoexx/github-action-json-file-properties@b9f36ce6ee6fe2680cd3c32b2c62e22eade7e590
        with: 
            file_path: "${{ env.packagePath }}/package.json"
            prop_path: "version"
    
      # パッケージのリリースに必要な環境変数を設定
      - name: 環境変数の設定
        run: |
          echo "zipFile=${{ vars.PACKAGE_NAME }}-${{ steps.version.outputs.value }}".zip >> $GITHUB_ENV
          echo "unityPackage=${{ vars.PACKAGE_NAME }}-${{ steps.version.outputs.value }}.unitypackage" >> $GITHUB_ENV
          echo "version=${{ steps.version.outputs.value }}" >> $GITHUB_ENV

      # リリース用にパッケージをZip化
      - name: パッケージZipの作成
        working-directory: "${{ env.packagePath }}"
        run: zip -r "${{ github.workspace }}/${{ env.zipFile }}" .
      
      # 将来使用するために.metaファイルのリストを作成
      - name: パッケージMetaファイルの追跡
        run: find "${{ env.packagePath }}/" -name \*.meta >> metaList
      
      # リリース用にパッケージのUnityPackageバージョンを作成
      - name: UnityPackageの作成
        uses: pCYSl5EDgo/create-unitypackage@cfcd3cf0391a5ef1306342794866a9897c32af0b
        with:
          package-path: ${{ env.unityPackage }}
          include-files: metaList
      
      # package.jsonファイルのバージョンからリリースタグを作成
      - name: タグの作成
        id: tag_version
        uses: rickstaa/action-create-tag@88dbf7ff6fe2405f8e8f6c6fdfd78829bc631f83
        with:
          tag: "${{ env.version }}"
      
      # リリースをGitHubに公開
      - name: リリースの作成
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844
        with:
          files: |
            ${{ env.zipFile }}
            ${{ env.unityPackage }}
            ${{ env.packagePath }}/package.json
          tag_name: ${{ env.version }}